name: CI

on: [push, pull_request, workflow_dispatch]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build Epoxy
        runs-on: ubuntu-latest
        steps:
            - run: sudo apt update
            - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            - run: source "$HOME/.cargo/env"
            - run: git clone https://github.com/mercuryworkshop/epoxy-tls
            - run: cd ./epoxy-tls
            - run: cargo b -r

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Linux build
                  path: ./epoxy-tls/target*
                  retention-days: 10